### ISSUE TITLE
mashlib load failure on main page

### ISSUE THREAD

**Issue by michielbdejong** [solid-contrib/pivot#15]
Outline.expand: Unable to fetch <https://localhost:8086/>: Failed to load  <https://localhost:8086/> Fetcher: <https://localhost:8086/> Unauthorized status: 401

**Comment by michielbdejong** [comment]
I think this happens when the user is not logged in.
Go to https://localhost:8086/.account/login/password/register/
But there are a lot of clicks to sign up (see #16) and after that this error still seems to happen on the site root.
Investigating.

**Comment by michielbdejong** [comment]
When I log in with solidcommunity.net instead of with localhost:8086 the error changes from a 401 to a 403.

I'm going to stop debugging this on localhost and use a Digital Ocean server instead, to rule out self-signed cert issues.

**Comment by bourgeoa** [comment]
@michielbdejong 
You could try https://github.com/SolidOS/css-mashlib/blob/main/package.json
`npm run start1` seems to work without issue

**Comment by michielbdejong** [comment]
Hm, it happens on https://pivot.pondersource.com/ as well.

**Comment by michielbdejong** [comment]
Indeed, `npm run start1` from https://github.com/SolidOS/css-mashlib works! Thanks. I'll find out what I'm doing differently here.

**Comment by michielbdejong** [comment]
The difference is that `npm run start1` doesn't use the subdomains config.

If I run:
```
npx community-solid-server -c ./config/https-mashlib-subdomain-file.json -f ./data --httpsKey /etc/letsencrypt/live/pivot.pondersource.com-0001/privkey.pem --httpsCert /etc/letsencrypt/live/pivot.pondersource.com-0001/fullchain.pem -p 443 -b https://pivot.pondersource.com
```
 from https://github.com/SolidOS/css-mashlib on pivot.pondersource.com then after signup https://michielbdejong.pivot.pondersource.com works, but the main page still doesn't.

The logs say:
```
2024-11-05T14:27:44.157Z [WebAclReader] {Primary} error: No ACL document found for root container https://pivot.pondersource.com/
2024-11-05T14:27:44.158Z [PermissionBasedAuthorizer] {Primary} warn: Unauthenticated agent has no read permissions
2024-11-05T14:27:44.246Z [HandlerServerConfigurator] {Primary} info: Received GET request for /
```

I'll see if I can manually create a "pod" for that main URL and put an ACL and a welcome page into it.

**Comment by bourgeoa** [comment]
You could look to https://solidcommunity.net:3000/ this is a subdomain testserver
I think it works has you want

Documentation is here with the config file https://github.com/solid/solidcommunity.net/wiki/solidcommunity.net-servers#1-css-subdomain-test-server--httpssolidcommunitynet3000

**Comment by bourgeoa** [comment]
sudomain and suffix do not use the same CSS config

**Comment by michielbdejong** [comment]
Thanks! I also found the `RootStorageLocationStrategy` config variable in the CSS code which might be relevant.
