### ISSUE TITLE
Preserve shorthand notation for RDF collections when applying a PATCH

### ISSUE THREAD

**Issue by michielbdejong** [solid-contrib/pivot#2]

**Comment by janschill** [comment]
A few references

- https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1438
- https://github.com/solid/specification/issues/342
- https://github.com/solid/specification/issues/465
- https://www.w3.org/DesignIssues/Pretty.html

**Comment by michielbdejong** [comment]
Ah ok so it's not only about displaying it nicely in an human-readable view, but also about preserving the whitespace, comments, etc.

**Comment by melvincarvalho** [comment]
Small note I think pretty printed turtle should have a space before the final `.` as canonical form.

**Comment by michielbdejong** [comment]
Will work on this tomorrow.

**Comment by michielbdejong** [comment]
I read the discussion in https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1438 - I think it would be good to focus on RDF list syntax first, and then see if there are any other requirements once that is supported.

Changing this issue's title to reduce its scope to just RDF lists and not syntax preservation in general which I think might be a more complex issue.

**Comment by melvincarvalho** [comment]
Good thing to fix.  Bear in mind that lists are one of the most difficult RDF primitives.  I personally prefer simple data structures that with JSON arrays, such as giving items an index, to avoid List issues.  Similarly I think RDFa support should be deprecated in favour of Turtle or JSON-LD.  But these are more suited to a best practice document or client/client standards.  Well, we have to support Lists for now, but they do add complexity.

**Comment by michielbdejong** [comment]
I found the spec for it in [RDF Schema 1.1](https://www.w3.org/TR/rdf-schema/#ch_collectionvocab):
>  There is a [shorthand notation](https://www.w3.org/TR/turtle/#collections) in the Turtle syntax specification for representing collections

I read some good arguments both in favour and against preserving them on PATCH:
In favour:
* The shorthand is useful for Turtle file readability, which is of considerable value to Solid Developer Experience.
* NSS preserves them, so not doing so in Pivot would feel like a regression

Against:
* It's not a spec requirement, so implementing it would give developers a false sense of security
* when serialising a huge quad stream to Turtle, a list's items might be scattered across the quad stream, so this would require arbitrarily large buffers to serialise.

My opinion:
* Regarding performance, I think we could just document for developers that if they want high performance for huge files, they can try their luck with low-level syntax for collections in turtle, or even just try a representation like n-quads. We don't have any data on this though, afaik.
* Regarding architecture invariants of using quad streams everywhere, they can be preserved if we're willing to do the do the work of serialising from quad streams to shorthand. We would however require somehow to remember which of the collections appeared in shorthand syntax and which ones appeared in low-level syntax in the Turtle file. I wonder how we do that currently for comments.
* Regarding spec strictness, I'm usually a big proponent of that but in this case I think it's clear that the community wants to use RDF lists, so our servers, especially the community server, should support it. I'll put it on the agenda for Wednesday's CG call: https://hackmd.io/-MWGn02kTRuOHfwf27t-GQ#Documenting-community-level-server-requirements

**Comment by michielbdejong** [comment]
I don't know how to patch a turtle document in the right way but I think rdflib.js does, and I think that's also what NSS uses for it, so let's use that.

**Comment by michielbdejong** [comment]
We'll diverge from [what is documented here](https://communitysolidserver.github.io/CommunitySolidServer/latest/architecture/features/protocol/patching/) for this.

**Comment by michielbdejong** [comment]
Need to remove `ConvertingPatcher` from the chain
