### ISSUE TITLE
CSS cannot PATCH lists [ ] 

### ISSUE THREAD

**Issue by bourgeoa** [solid-contrib/pivot#31]
@timbl @michielbdejong 

In `/preferences/` `Manage your Trusted App` I tried to add `https://podpro.dev`
This should insert
```
:me acl:trustedApp
            [
                acl:mode acl:Append, acl:Control, acl:Read, acl:Write;
                acl:origin <https://podpro.dev>] 
```
but failed with error 422. Some details

Preview
```
	{name: "UnprocessableEntityHttpError",…}
	details
	: 
	{}
	errorCode
	: 
	"H422"
	message
	: 
	"An N3 Patch delete/insert formula can not contain blank nodes."
	name
	: 
	"UnprocessableEntityHttpError"
	statusCode
	: 
	422
```
Payload
```
	@prefix solid: <http://www.w3.org/ns/solid/terms#>.
	@prefix ex: <http://www.example.org/terms#>.

	_:patch

		  solid:inserts {
			<https://bourgeoa2.solidcommunity.net:8443/profile/card#me> <http://www.w3.org/ns/auth/acl#trustedApp> _:bn_wrjr7 .
			_:bn_wrjr7 <http://www.w3.org/ns/auth/acl#origin> <https://podpro.dev> .
			_:bn_wrjr7 <http://www.w3.org/ns/auth/acl#mode> <http://www.w3.org/ns/auth/acl#Read> .
			_:bn_wrjr7 <http://www.w3.org/ns/auth/acl#mode> <http://www.w3.org/ns/auth/acl#Write> .
			_:bn_wrjr7 <http://www.w3.org/ns/auth/acl#mode> <http://www.w3.org/ns/auth/acl#Append> .
			_:bn_wrjr7 <http://www.w3.org/ns/auth/acl#mode> <http://www.w3.org/ns/auth/acl#Control> .
		  };   a solid:InsertDeletePatch .
```

**Comment by michielbdejong** [comment]
Thanks for spotting this! I think maybe this patch is actually incorrect. The `_:patch` in the subject is fine,  but why is there a blank node `_:bn_wrjr7` in there? Can we change mashlib so that it uses a named node there?

CSS indeed [checks this](https://github.com/CommunitySolidServer/CommunitySolidServer/blob/9647882cf389edccd50edfb7d8ab568b401883ad/src/http/input/body/N3PatchBodyParser.ts#L113-L137)

And the spec indeed [specifies this](https://solidproject.org/TR/protocol#server-patch-n3-blank-nodes)

**Comment by michielbdejong** [comment]
Ah, I went for a different approach in https://github.com/solidos/solid-panes/pull/390, namely using a named node instead of a blank one for this thing:
```ttl

                            [
                                acl:origin <https://podpro.dev>;
                                acl:mode
                                acl:Read, acl:Write, acl:Append, acl:Control
                            ].
```

**Comment by michielbdejong** [comment]
I think we can consider this fixed, right @bourgeoa? Or are there still new conversations I'm unaware of?

**Comment by bourgeoa** [comment]
Agree to close.
I shall open an issue in Rdflib
