### ISSUE TITLE
Create configuration that exposes port 8086

### ISSUE THREAD

**Issue by michielbdejong** [solid-contrib/pivot#5]
For use on solidcommunity.net

**Comment by michielbdejong** [comment]
See also https://github.com/CommunitySolidServer/Recipes/issues/31

**Comment by michielbdejong** [comment]
@thhck can you have a look today?
@janschill did you have a chance to look at it yesterday in the train?

**Comment by janschill** [comment]
> @thhck can you have a look today? @janschill did you have a chance to look at it yesterday in the train?

I had a spotty connection. I was only able to get a bit more familiar with the current NSS deployment. Nothing reportable. Continuing a bit more now

**Comment by michielbdejong** [comment]
Looks like @bourgeoa got it working
https://matrix.to/#/!VAJLTawStGAyYwzTTY:gitter.im/$F2KdIjuhNKNUxdRHl7lYR2zxA_ArGHP5wB_PtBwtdxs?via=gitter.im&via=matrix.org&via=attendees.fosdem.org
We have a video call tomorrow morning 10:30am CET

**Comment by michielbdejong** [comment]
Done, see https://cloud.pondersource.com:8086 and https://github.com/solid-contrib/pivot#example-usage as an example.
